AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: java8
    Timeout: 60
    MemorySize: 1024
    Handler: net.kkhstudy.myfirstlambda.handler.DemoFunctionHandlerRest
    Environment:
      Variables:
        TABLE_NAME: DemoEntity
        MAIN_CLASS: net.kkhstudy.myfirstlambda.MyFirstLambdaApplication
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  DemoEntityTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: name
        Type: String
      TableName: DemoEntity
  CreateEntityFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      #Runtime: java8
      #Handler: de.margul.awstutorials.DemoFunctionHandler::handleRequest
      #Timeout: 60
      Description: Creates new demo entities
      CodeUri: ./target/my-first-lambda-0.0.1-SNAPSHOT-aws.jar
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DemoEntityTable
      Environment:
        Variables:
          FUNCTION_NAME: createEntityFunction
          SPRING_PROFILES_ACTIVE: aws
      Events:
        CreateEntityApi:
          Type: Api
          Properties:
            Path: /updateEntitie
            Method: POST
  GetEntityFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Fetch a demo entity by its name
      Environment:
        Variables:
          FUNCTION_NAME: getEntityFunction
          SPRING_PROFILES_ACTIVE: aws
      CodeUri: ./target/my-first-lambda-0.0.1-SNAPSHOT-aws.jar
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DemoEntityTable
      Events:
        GetEntityApi:
          Type: Api
          Properties:
            Path: /getEntitie
            Method: POST