AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Cloud Functions.
Resources:
  AwsLambdaTestLocal:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-lambda-sqs
      Handler: net.kkhstudy.myfirstlambda.TestHandler
      Description: For AWS Lambda Test
      Runtime: java8
      CodeUri: .\target\my-first-lambda-0.0.1-SNAPSHOT-aws.jar
      MemorySize: 320
      Timeout: 120
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: local