AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Cloud Functions.
Globals:
  Function:
    Runtime: java8
    Timeout: 20
    MemorySize: 320
    Handler: net.kkhstudy.myfirstlambda.handler.DemoFunctionHandlerRest
    Environment:
      Variables:
        TABLE_NAME: DemoEntity
        MAIN_CLASS: net.kkhstudy.myfirstlambda.MyFirstLambdaApplication
Resources:
  CreateEntityFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      #Runtime: java8
      #Handler: de.margul.awstutorials.DemoFunctionHandler::handleRequest
      #Timeout: 60
      Description: Creates new demo entities
      CodeUri: .
      Environment:
        Variables:
          FUNCTION_NAME: createEntityFunction
          SPRING_PROFILES_ACTIVE: local
      Events:
        CreateEntityApi:
          Type: Api
          Properties:
            Path: /entities
            Method: POST
  GetEntityFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Fetch a demo entity by its name
      Environment:
        Variables:
          FUNCTION_NAME: getEntityFunction
          SPRING_PROFILES_ACTIVE: local
      CodeUri: .
      Events:
        GetEntityApi:
          Type: Api
          Properties:
            Path: /entities/{name}
            Method: GET