AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Cloud Functions.
Resources:
  AwsLambdaFunctionLocal:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aws-lambda-sqs
      Handler: net.kkhstudy.myfirstlambda.AwsLambdaFunctionHandler
      Description: For AWS Lambda Test
      Runtime: java8
      CodeUri: .
      MemorySize: 320
      Timeout: 120
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: local
      Events:
        AwsLambdaFunction:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /awsLambdaFunction
            Method: get